### ISSUE TITLE
整理 9/23 會議紀錄

### ISSUE THREAD

**Issue by walle45611** [walle45611/NTUB_SecuManage#20]

**Comment by XiaoXian1016** [comment]
# 9/23 會議紀錄

1. **專案進度**：後端架構與Model (Entity) 已確定。
   
2. **專案結構**：
   - **Application**：包含API的Endpoint與Schema，Schema定義API的傳入與回傳資料格式。
   - **Core**：存放應用程式的Config與Database Session連接程式。
   - **Domain**：包含Model（Entity）與Service，Service處理核心商業邏輯。
   - **Infrastructure**：包含Migrations與Repositories，Repositories負責對Entity的操作，如GetAll、Create、GetByID等。
