### ISSUE TITLE
整理第一次開會紀錄

### ISSUE THREAD

**Issue by walle45611** [walle45611/NTUB_SecuManage#9]

**Comment by XiaoXian1016** [comment]
9/16會議記錄重點整理如下：

---

**1. 已完成部分與操作建議**

- 目前已有部分功能由廠商完成，帳號和密碼將會提供，但建議僅查看，避免過多操作。
- 如需操作，可自行新增和刪除資料。

---

**2. 系統功能簡述**

- **最新消息**：包含系統填報時間及法規資訊，管理者可發布。
- **文件管理**：北商的所有程序書與表單都在此區域管理。
- **資產盤點**：分為六大類，涵蓋文件、資料、電腦系統、人員、服務及實體設備。各類資產的收集欄位相似，部分根據資產性質調整。
- 系統以**PDCA流程**運行，包含文件創建、系統分級、風險評鑑等。

---

**3. 資產與風險評鑑流程**

- 系統將進行分級，依據機密性、完整性、可用性及法律遵循性來評定。
- 資產盤點：可從系統或其他非系統資產進行，像是學校內的某些人員也需納入。
- 風險評鑑從資訊資產盤點和個資盤點進行，涵蓋脆弱點、威脅及衝擊分析。
- 目前廠商專注於資料收集，但主任更關注**簽核**與**追跡16會議記錄重點整理如下：

---

**1. 已完成部分與操作建議**

- 目前已有部分功能由廠商完成，帳號和密碼將會提供，但建議僅查看，避免過多操作。
- 如需操作，可自行新增和刪除資料。

---

**2. 系統功能簡述**

- **最新消息**：包含系統填報時間及法規資訊，管理者可發布。
- **文件管理**：北商的所有程序書與表單都在此區域管理。
- **資產盤點**：分為六大類，涵蓋文件、資料、電腦系統、人員、服務及實體設備。各類資產的收集欄位相似，部分根據資產性質調整。
- 系統以**PDCA流程**運行，包含文件創建、系統分級、風險評鑑等。

---

**3. 資產與風險評鑑流程**

- 系統將進行分級，依據機密性、完整性、可用性及法律遵循性來評定。
- 資產盤點：可從系統或其他非系統資產進行，像是學校內的某些人員也需納入。
- 風險評鑑從資訊資產盤點和個資盤點進行，涵蓋脆弱點、威脅及衝擊分析。
- 目前廠商專注於資料收集，但主任更關注**簽核**與**催稽**的部分。

---

**4. 系統擴展與弱點威脅對應**

- 資產盤點的弱點與威脅對應分為六大類，如人員、服務、軟體、實體、資料、文件。
- 每個資產類型會對應多個弱點、威脅和控制措施。
- 簽核與資產盤點的資料匯入是系統的重要功能。

---

**5. 簽核流程與催稽功能**

- 資訊系統分級需簽核，從承辦人提交到主管，再由各單位的資安窗口確認。
- **簽核功能**能追蹤各部門的處理狀態，避免資料遺漏。
- 如果系統中加入簽核和催稽功能，能更好地管理任務流程和資訊系統的進度。

---

**6. 資料控制與報表顯示**

- 使用者須匯入資產類型、弱點、威脅等資料，之後才能顯示資產報表。
- 各單位的需求不同，欄位可能擴充，系統需具備彈性來應對。

---

**7. 資安系統與公文系統整合**

- 資安系統與公文系統都需保存資料，簽核流程文件應保存至資產盤點中。
- 簽核與控制資料會保留於資產標籤內，以備檢查。
